service: microservicio-resenas

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::385301667309:role/LabRole
  environment:
    RESENIAS_TABLE: Resenas  # Asegúrate que el nombre de la tabla sea correcto

functions:
  crearResena:
    handler: handler.crearResena
    events:
      - http:
          path: resenas
          method: post

resources:
  Resources:
    ResenasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Resenas  # Nombre de la tabla
        AttributeDefinitions:
          - AttributeName: tenant_id_producto_id  # Clave de partición
            AttributeType: S
          - AttributeName: resenia_id  # Clave de ordenamiento
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id_producto_id  # Clave de partición
            KeyType: HASH
          - AttributeName: resenia_id  # Clave de ordenamiento
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST  # Modo de facturación sin necesidad de provisión de capacidad
