service: microservicio-resenas

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::385301667309:role/LabRole 
  environment:
    TABLE_NAME: Resenas

functions:
  crearResena:
    handler: handler.crearResena
    events:
      - http:
          path: resenas
          method: post
  obtenerResenas:
    handler: handler.obtenerResenas
    events:
      - http:
          path: resenas/{tenant_id}/{producto_id}
          method: get
  actualizarResena:
    handler: handler.actualizarResena
    events:
      - http:
          path: resenas
          method: put
  eliminarResena:
    handler: handler.eliminarResena
    events:
      - http:
          path: resenas
          method: delete

resources:
  Resources:
    ResenasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Resenas
        AttributeDefinitions:
          - AttributeName: tenant_id#producto_id
            AttributeType: S
          - AttributeName: resenia_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id#producto_id
            KeyType: HASH
          - AttributeName: resenia_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
