org: dannamendez
service: api-resenia

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::385301667309:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_resenias

functions:
  crear:
    handler: resenia.crearResenia
    events:
      - http:
          path: /resenia/crear
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TablaResenias:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_producto_id
            AttributeType: S  # Combinación de tenant_id y producto_id
          - AttributeName: resenia_id
            AttributeType: S
          - AttributeName: fecha
            AttributeType: S  # Fecha de la reseña (puede ser un string de tipo ISO8601)
        KeySchema:
          - AttributeName: tenant_producto_id
            KeyType: HASH  # Clave de partición (combinación tenant_id#producto_id)
          - AttributeName: resenia_id
            KeyType: RANGE  # Clave de ordenamiento (resenia_id único)
        BillingMode: PAY_PER_REQUEST
        LocalSecondaryIndexes:
          - IndexName: FechaIndex
            KeySchema:
              - AttributeName: tenant_producto_id
                KeyType: HASH  # Clave de partición (debe ser la misma que la principal)
              - AttributeName: fecha
                KeyType: RANGE  # Clave de ordenamiento secundaria para ordenar por fecha
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: UsuarioIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: usuario_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
