org: ${env:ORG}
service: api-tienda

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:IAM_ROLE_ARN}  # ARN del rol LabRole
  environment:
    TIENDA_TABLE: ${self:service}-${sls:stage}-tienda  # Usamos la variable `${self:service}` para obtener el nombre del servicio y `${sls:stage}` para el entorno

  httpApi:
    cors:
      allowedOrigins:
        - '*'  # Permite cualquier origen
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      allowedMethods:
        - OPTIONS
        - GET
        - POST
      allowCredentials: false

functions:
  createProduct:
    handler: create_tienda.handler
    events:
      - http:
          path: /tienda/create
          method: post
          cors: true
          integration: lambda

  fetchProduct:
    handler: fetch_tienda.handler
    events:
      - http:
          path: /tienda/fetch
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TiendaTable:  # Nombre del recurso de la tabla DynamoDB
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-tienda  # El nombre de la tabla se genera de manera similar
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
