org: dannamendez
service: api-tienda

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::385301667309:role/LabRole  # ARN del rol LabRole
  environment:
    TIENDA_TABLE: ${sls:stage}-tienda

functions:
  createTienda:
    handler: create_tienda.handler
    events:
      - http:
          path: /tienda/create
          method: post
          cors: true
          integration: lambda

  fetchTienda:
    handler: fetch_tienda.handler
    events:
      - http:
          path: /tienda/fetch
          method: get
          cors: true
          integration: lambda


resources:
  Resources:
    TiendaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TIENDA_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
