org: ${env:ORG}
service: api-tienda

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:IAM_ROLE_ARN}  # ARN del rol LabRole
  environment:
    TIENDA_TABLE: ${self:service}-${sls:stage}-tienda  # Usamos la variable `${self:service}` para obtener el nombre del servicio y `${sls:stage}` para el entorno


functions:
  createProduct:
    handler: create_tienda.handler
    events:
      - http:
          path: /tienda/create
          method: post
          cors:
            origin: '*'  # Permitir cualquier origen
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
          integration: lambda

  fetchProduct:
    handler: fetch_tienda.handler
    events:
      - http:
          path: /tienda/fetch
          method: get
          cors:
            origin: '*'  # Permitir cualquier origen
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
          integration: lambda

resources:
  Resources:
    TiendaTable:  # Nombre del recurso de la tabla DynamoDB
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-tienda  # El nombre de la tabla se genera de manera similar
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
